### ISSUE TITLE
Auto Content

### ISSUE THREAD

**Issue by Da-Fecto** [adrianbj/AutoContent#1]
When un-installing, the module tries to delete the autocontent folder. When this folder doesn't exists, an error is thrown.

RecursiveDirectoryIterator::__construct(/Users/martijn/Sites/Domains/keukenspecialist.dev/htdocs/site/assets/autocontent/): failed to open dir: No such file or directory

**Comment by adrianbj** [comment]
Thanks @Da-Fecto - I just committed a fix.

I hope you were uninstalling because your site was going live, not because the module was no good :) I am planning on giving this module some more love shortly - I want to improve content rendering for content called from page fields, and also likely remove the called to the loripsum external service to speed things up there too.

**Comment by Da-Fecto** [comment]
@adrianbj, I had/have to rebuild an already existing site. In the end I ended up scraping that site with WireHttp. :-) and some DomDocument shizzle.
Ps, I would love to see a callable API to get the Ipsum Text (if it's not already in there :-))
Greetz Martijn

Thanks fixing it !
